language: cpp
sudo: required
branches:
  except: "/pr\\/.*/"

env:
  global:
  # Twine env variable
  - secure: aEdXByDIGucKP4PhkSLnuM0cyWtXqu1xu2N+/hT1HkaUBtRurhY3/QtOTPYg7BxLDp9HUJeOrIDfPW0RD5yHadiQMbQpqnfSoTBEj4jKK9TE6c9Vw/ZURmhueUsGM4og4weIbgm8JF9dJQeu+3GBBW8JJYkYQMYhmr0gV+gPwBVYPzr0c5joUH+ZUA/WqIMJBgmR1qN42C615xX1cWkhLf2kDDL5zM8T+P7ZIesz9gHvWwptkleaGPppkqliIOHWsD/LLLajk89yVh290FHVxaFThoTk3sdQJteTt2qq6g4Y2H+IP0vseQ4JmWHSRWFOSZts21ZZVeUchfCiPEbYyHJxRI+vSXrkAOktujkfWum3OmiVEZczTQ9mJ+Mn6sgGvvu6935H44vvV6Nn5qnkoUMJmXdkrPDFxPtAuS2sI+is8NWMRpgfjhHEA05BQw/CTAQW5RjnI4qYNRaLPgHeQc4rbfg5Xgg5VkI2miFN7zqSEO4WDlqbHe6GbumpnuMMInOZZurOm1WpBCDZrbAiWwiuopygr6vPMwBw2fE0kGUBQJTnBgd6a+ZQik1Fgj5mcFmYLYZ8RY8wuqhaJc9Ndye8vG7dTSx2XYjw/6JP4fbsTJg+SLWKIs1i/llKgMkmxh3aACaWG3B8VGXijkEvYzqAkmM/Z9NwZlLd9kBjyUE=

matrix:
  include:
    - env: DCGP_BUILD="DebugGCC"
      dist: bionic
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - binutils-gold
    - env: DCGP_BUILD="ReleaseGCC"
      dist: bionic
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - binutils-gold
    - env: DCGP_BUILD="CoverageGCC"
      dist: bionic
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packa1ges:
          - binutils-gold
    # These are to be uncommented when the quadmath issue is understood and fixed (maybe upstream?)
    # These builds fail as per a not found quadmath.h ... its not clear why or how
    #- env: DCGP_BUILD="ReleaseClang"
    #  dist: bionic
    #  compiler: clang
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #      - ubuntu-toolchain-r-test
    #      packages:
    #      - clang-7
    #- env: DCGP_BUILD="DebugClang"
    #  dist: bionic
    #  compiler: clang
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #      - ubuntu-toolchain-r-test
    #      packages:
    #      - clang-7
    - env: DCGP_BUILD="Python37"
      dist: bionic
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
    - env: DCGP_BUILD="Python27"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
    - env: DCGP_BUILD="OSXDebug"
      os: osx
    - env: DCGP_BUILD="OSXRelease"
      os: osx
    # These are Commented as per a weird segfault that must be investigated ....
    #- env: DCGP_BUILD="OSXPython37"
    #  os: osx
    #  #osx_image: xcode6.4
    #- env: DCGP_BUILD="OSXPython27"
    #  os: osx
    #  #osx_image: xcode6.4
    - env: DCGP_BUILD="manylinux64Py37" DOCKER_IMAGE="pagmo2/manylinux1_x86_64_with_deps"
      sudo: required
      services:
      - docker
    - env: DCGP_BUILD="manylinux64Py36" DOCKER_IMAGE="pagmo2/manylinux1_x86_64_with_deps"
      sudo: required
      services:
      - docker
    - env: DCGP_BUILD="manylinux64Py27" DOCKER_IMAGE="pagmo2/manylinux1_x86_64_with_deps"
      sudo: required
      services:
      - docker
    - env: DCGP_BUILD="manylinux64Py27mu" DOCKER_IMAGE="pagmo2/manylinux1_x86_64_with_deps"
      sudo: required
      services:
      - docker
script:
    - mkdir build
    - cd build
    # NOTE: currently, travis does not stop automatically if one of these
    # 2 scripts returns an error code. Thus, we run them together as a single
    # command, so that if install_deps.sh fails the whole build fails immediately
    # rather than executing install_travis.sh as well. See
    # https://github.com/travis-ci/travis-ci/issues/1066
    - ../tools/install_deps.sh && ../tools/install_travis.sh
notifications:
  email: false


